server {
    listen 80;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Dòng quan trọng nhất để không bị lỗi 404 khi nhấn F5
        try_files $uri $uri/ /index.html; 
    }
}